### ISSUE TITLE
 interfaces => undef dosent remove the -i inn the startup command

### ISSUE THREAD

**Issue by CyberSecDog** [odinje/puppet-suricata#3] opened 2017-10-13 11:57 UTC
if i use
class { ::suricata:
  interfaces => undef,
}

the execstart command is "-i <my first interface>" I want to remove it.
this is what I need.
ExecStart=/usr/bin/suricata -c /etc/suricata/suricata.yaml  --user suricata  --af-packet

**Comment by odinje** [comment] 2017-10-20 12:37
As I look into the problem does it looks like that the undef is not set since there exists i value for interfaces. I have now changed the documentation to set interfaces to => false.  

I have tested it, and it should work now. However, I will remain this issue open to you have confirmed that it works for you.

**Comment by odinje** [comment] 2017-12-04 00:36
Closing this since it seem to be fixed.

**Closed as completed by odinje** 2017-12-04 00:36 UTC
Labels: bug
